### ISSUE TITLE
ValueError: Cannot resolve: No module named 'opensearch_logger' in Django

### ISSUE THREAD

**Issue by shivam74633** [vduseev/opensearch-logger#5] opened 2022-12-26 16:01 UTC
I have installed the package but not able to use it
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.8/logging/config.py", line 721, in configure_handler
    klass = self.resolve(cname)
  File "/usr/lib/python3.8/logging/config.py", line 397, in resolve
    raise v
  File "/usr/lib/python3.8/logging/config.py", line 390, in resolve
    self.importer(used)
ValueError: Cannot resolve 'opensearch_logger.OpenSearchHandler': No module named 'opensearch_logger.OpenSearchHandler'
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/uslsz367/ewa_env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/uslsz367/ewa_env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/uslsz367/ewa_env/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/uslsz367/ewa_env/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/uslsz367/ewa_env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/uslsz367/ewa_env/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/uslsz367/ewa_env/lib/python3.8/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'opensearch'
```

**Comment by vduseev** [comment] 2022-12-26 23:22
Hi @shivam74633, thank you for reporting the issue.

However, I struggle to figure out an underlying problem, if any, based on the reported stack trace. I would be very grateful if you could provide me with more information on how you launch your Django application as well as some other details.

What your stack trace is showing is that Django, for some unknown reason, failed to find the `opensearch_logger` package in the Python environment. That could happen for bazillion reasons, but some of the most frequent ones are:

* Package have not actually been installed into the virtual environment or into the system installation of Python, or conda, depending on how you do things.
* The main program entry point has been launched outside of virtual environment (a.k.a. forgot to active virtual environment). That wouldn't normally happen, because then Python wouldn't be able to find Django as well. But sometimes, people install Django into their system python and the rest of the packages are installed into a virtual environment. Then, without activating the venv, Django is launched fine but fails to find rest of the packages.
* Django or program's code does something with the sys.path variable prior to the package being imported.
* ... and so on and so on; and finally
* Package is actually not working with Django.

I've tested this package with a [simple Django application](https://github.com/vduseev/opensearch-logger-issue-5) and was able to reproduce your issue, but only when the package **was not installed at all** in the project's virtual environment:

*The stack trace below is generated for a project where only `django` is installed, without `opensearch-logger`*.

As soon as I have installed the `opensearch-logger` package into the same environment, everything worked and the index was created in OpenSearch and log records have appeared.

```python
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/vduseev/.pyenv/versions/3.11.0/lib/python3.11/logging/config.py", line 385, in resolve
    found = self.importer(used)
            ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'opensearch_logger'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vduseev/.pyenv/versions/3.11.0/lib/python3.11/logging/config.py", line 562, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vduseev/.pyenv/versions/3.11.0/lib/python3.11/logging/config.py", line 724, in configure_handler
    klass = self.resolve(cname)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/vduseev/.pyenv/versions/3.11.0/lib/python3.11/logging/config.py", line 396, in resolve
    raise v from e
ValueError: Cannot resolve 'opensearch_logger.OpenSearchHandler': No module named 'opensearch_logger'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vduseev/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/vduseev/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/vduseev/Projects/Playground/opensearch-logger-django-bug/.venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/vduseev/Projects/Playground/opensearch-logger-django-bug/.venv/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/vduseev/Projects/Playground/opensearch-logger-django-bug/.venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/vduseev/Projects/Playground/opensearch-logger-django-bug/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/vduseev/Projects/Playground/opensearch-logger-django-bug/.venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/vduseev/Projects/Playground/opensearch-logger-django-bug/.venv/lib/python3.11/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/vduseev/Projects/Playground/opensearch-logger-django-bug/.venv/lib/python3.11/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/Users/vduseev/.pyenv/versions/3.11.0/lib/python3.11/logging/config.py", line 812, in dictConfig
    dictConfigClass(config).configure()
  File "/Users/vduseev/.pyenv/versions/3.11.0/lib/python3.11/logging/config.py", line 569, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'opensearch'
```

Information that could help with debugging this issue further:
* **Making sure that the `opensearch-logger` package is actually installed in the same environment where the application runs.** 
* Your Django logging configuration
* Your platform environment information
  * OS and platform (x86, x64, arm, etc)
  * Python version
  * Django version
  * opensearch-logger version you've chosen
* How you launch your Django application
  
The easiest way to debug this on my side would be if you could provide a minimal application that reproduces the problem in your environment.

You will find all the details, including a complete reproduction of the problem, which occurs when `opensearch-logger` is not installed as well as a simplest working loggin setup with `django` and `opensearch-logger` in this repository created for investigation of this issue: [github.com/vduseev/opensearch-logger-issue-5](https://github.com/vduseev/opensearch-logger-issue-5).

**Comment by vduseev** [comment] 2023-01-29 04:44
Going to close this as there was no follow up from the original reporter and the issue is caused by the library not being installed.

**Closed by vduseev** 2023-01-29 04:44 UTC
Labels: django
